### ISSUE TITLE
Get Started ページの表示について

### ISSUE THREAD

**Issue by Reputeless** [nokotan/siv3d-studio#11]
Get Started ページが Main.cpp 読み込み完了（1～3 秒程度）後に消えてしまう問題。

- そもそも Get Started を表示しない
- Main.cpp と両立させる

のいずれかを検討する。

**Comment by nokotan** [comment]
> * Get Started を表示しない

VSCode の起動オプションとしては提供されていませんでした。
DefaultConfiguration で初期画面を指定(`workbench.startupEditor`)しても、無視するような挙動を取りました

とりあえず、Get Started を消さずに Main.cpp を表示するようにしてみます

**Comment by nokotan** [comment]
```json
"workbench.startupEditor": "readme"
```
で Get Started ページの代わりに、README を表示させてみようとしましたが、
README.md ファイルの読み込みが初期画面の表示までに間に合わないようです
