### ISSUE TITLE
アプリプログラムの終了をわかりやすく伝える

### ISSUE THREAD

**Issue by Reputeless** [nokotan/siv3d-studio#12]
- priority: medium

下記の状態について、いずれも実行画面が固まるので、もう少し親切に通知したい。

- Main() 関数の終了
- 例外等による異常終了

**Comment by nokotan** [comment]
- 正常終了時
  - [x] リロードボタンを表示する
- 異常終了時
  - [x] エラーの内容を通知
  - [x] リロードボタンを表示する
- [x] リロードボタンでリロードできるようにする
