### ISSUE TITLE
エラーメッセージを色付けで読みやすく

### ISSUE THREAD

**Issue by Reputeless** [nokotan/siv3d-studio#17]
- priority: low

`error` が含まれる行を赤くするなど、単純な仕組みで良い。

似たような VS 拡張:  https://marketplace.visualstudio.com/items?itemName=MikeWard-AnnArbor.VSColorOutput

**Comment by nokotan** [comment]
VSCode, clang ともに `-fcolor-diagnostics` に対応していたので、コンパイルオプションを追加しました
