### ISSUE TITLE
エディタの日本語フォントを改善する

### ISSUE THREAD

**Issue by Reputeless** [nokotan/siv3d-studio#2]
- priority: medium

Windows 11 + Google Chrome / Firefox でのエディタの表示:
![image](https://user-images.githubusercontent.com/3108136/186839421-8b814375-fb75-4bc1-885b-9e2d01935541.png)

**Comment by nokotan** [comment]
どのようなフォントが望ましいかの情報がなければ、どうしようもありません

**Comment by Reputeless** [comment]
例えば `Meiryo` など。ただし、コード部分はコーディング用フォントが維持されるよう注意。
