### ISSUE TITLE
Firefox でプレビューが起動しない

### ISSUE THREAD

**Issue by Reputeless** [nokotan/siv3d-studio#24]
![image](https://user-images.githubusercontent.com/3108136/187659548-e16a18c8-38fc-4dd7-b776-b4c6a35291dd.png)

```
Error loading webview: Error: Could not register service workers: SecurityError: The operation is insecure..
```

- Windows 11
- Firefox 104.0.1

**Comment by nokotan** [comment]
FireFox でのデフォルトのセキュリティ設定が関係していそうです

VsCode では [WebView が機能しないという Issue](https://github.com/microsoft/vscode/issues?q=is%3Aissue+register+service+worker+) で大量に投稿されています

しかし、 Siv3D Studio/VSCode でどうにかできるという問題でもなく、ブラウザのセキュリティ方針であり、回避策はなさそうな雰囲気があります

Chrome/FireFox のプライベートブラウジングでも発生し、これも回避不能のようです

> Firefox では[プライベートブラウジングモード](https://support.mozilla.org/ja/kb/private-browsing-use-firefox-without-history)でサービスワーカー API を利用することはできません。

参考: [mdn サービスワーカ API](https://developer.mozilla.org/ja/docs/Web/API/Service_Worker_API)

**Comment by Reputeless** [comment]
いつの間にか Windows 11 + Firefox (107.0) で動作するようになっていました。
プライベートブラウジングでは引き続き NG です。

![image](https://user-images.githubusercontent.com/3108136/204591494-cd3729fb-cb33-4f8a-8175-5477d431d7e9.png)

**Comment by nokotan** [comment]
> プライベートブラウジングでは引き続き NG です。

上述した通り、回避不能です。
