### ISSUE TITLE
ビルドリクエストが集中していることを適切にユーザに通知する

### ISSUE THREAD

**Issue by Reputeless** [nokotan/siv3d-studio#29]
ビルドのリクエストが集中した場合の挙動について説明してください。
利用者向けの通知方法についても整理したいです。

**Comment by nokotan** [comment]
> ビルドのリクエストが集中した場合の挙動について説明してください。

"何の" 挙動の説明が欲しいのか曖昧なので、次の2点から現状をお伝えします。

* Siv3D Studio 上では、ビルドタスクが終了しないように見えています。
* ブラウザから見ると、ビルドタスクのリクエスト通信が途中で切れて、ブラウザはこれを通信エラーとしてハンドルしています。

> 利用者向けの通知方法についても整理したいです。

その通信エラーを適切にハンドルできれば、"ビルドタスクがコンパイルサーバによって中断されました。再度お試しください。" などの表示が可能です。

**Comment by nokotan** [comment]
https://github.com/nokotan/emscripten-remote-build/blob/main/src/wasm-studio/compilerServices/sendRequest.ts#L96-L113
