### ISSUE TITLE
ロードが終わらない現象が発生する

### ISSUE THREAD

**Issue by Reputeless** [nokotan/siv3d-studio#31]
Windows 11 + Google Chrome で Siv3D Studio にアクセスすると添付画像の状態が無限に続く現象が（数時間ぶりにアクセスするケースで）ちょくちょく起こります。

![image](https://user-images.githubusercontent.com/3108136/204485676-759a85f7-8486-4241-80c1-4f35a6ba9a42.png)

スクリーンショットは 11/19 時点

あきらめてスーパーリロードすると 5 秒程度でコーディング可能になります（この時間は以前と変わらず）。

それぞれのコンソールログを添付します（2 ファイル）
https://gist.github.com/Reputeless/7051553fed104893ac5a347c6a87d6c7

上記以外で同じ現象が起こるかは未検証です。

**Comment by nokotan** [comment]
再現しません。必要があれば Reopen してください。
