### ISSUE TITLE
一度読み込むまで FileSystem::IsFile が true を返さない

### ISSUE THREAD

**Issue by Raclamusi** [nokotan/siv3d-studio#34]
一度も読み込まれてないファイルに対して `FileSystem::IsFile` が false を返します。

```c++
# include <Siv3D.hpp>

void Main()
{
	Print << FileSystem::IsFile(U"example/windmill.png");

	const Texture texture{ U"example/windmill.png" };

	Print << FileSystem::IsFile(U"example/windmill.png");

	while (System::Update())
	{
		texture.drawAt(Scene::Center());
	}
}
```

![image](https://user-images.githubusercontent.com/61970673/210558827-94b4dba0-f3eb-4679-9c5c-9cc8dd91c3ac.png)

**Comment by Raclamusi** [comment]
`FileSystem::Exists` や `FileSystem::IsDirectory` などについても同様です。

**Comment by nokotan** [comment]
[Siv3D Web版のファイルシステムの制約です](https://siv3d.kamenokosoft.com/ja/trouble-shooting/web-specific-notes#%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB%E3%82%B7%E3%82%B9%E3%83%86%E3%83%A0)。
Texture のコンストラクタでは内部的に [Platform::Web::FetchFile](https://siv3d.kamenokosoft.com/ja/trouble-shooting/web-specific-functions#%E3%82%B5%E3%83%BC%E3%83%90%E3%81%8B%E3%82%89%E8%BF%BD%E5%8A%A0%E3%81%AE%E3%82%A2%E3%82%BB%E3%83%83%E3%83%88%E3%82%92%E3%83%80%E3%82%A6%E3%83%B3%E3%83%AD%E3%83%BC%E3%83%89%E3%81%99%E3%82%8B) を呼んでいるため、コンストラクタを呼ぶ前はファイルが仮想ファイルシステム上に存在しないこととなります。
デスクトップ版と比べると直感に反するのは同意ですが、対応するとなると影響範囲が大きすぎるため、かなり時間がかかります。

**Comment by Raclamusi** [comment]
手元の Siv3D for Web (0.6.5, VisualStudio) ではこの問題は発生しなかったのですが、 Siv3D for Web では example のファイルの埋め込みを行っているが Siv3D Studio では埋め込みは行わず必要な時にフェッチしているということですか？

**Siv3D for Web (VisualStudio) での実行結果**

![image](https://user-images.githubusercontent.com/61970673/210702817-302c0ea6-0f48-4dc4-9ce4-321d194aaf2b.png)

**Comment by nokotan** [comment]
埋め込みが行えない、ということです

**Comment by nokotan** [comment]
ここからは補足です。

### Siv3D for Web と Siv3D Studio のビルド方法の違い

Siv3D for Web では、出力される *.js, *wasm ファイルを最小にするために、すべてのライブラリを静的リンクします。

しかし、 Siv3D Studio ではコンパイル時間を最小にするために、Siv3D 本体と Main 関数を含むユーザコードを別々にリンクします。Siv3D Studio 上では、Siv3D.wasm, main.wasm と 2 つ *.wasm ファイルが存在しており、実行時に動的リンクを行います。

### 動的リンクの制約

Siv3D for Web のコンパイルバックエンドに使っている emscripten の制約上、リンク時にアセットファイルの埋め込みを行う機会は一度しかありません。(詳しくは、Main Module, Side Module で調べてください。)

これはつまり、Siv3D.wasm をリンクするとき、または、main.wasm をリンクするときのどちらかのタイミングでしか、アセットファイルの埋め込みができないということを意味します。

### Siv3D Studio で採用している方法

Siv3D Studio では、コンパイル時間のより短くなる、Siv3D.wasm をリンクするときにアセットファイルの埋め込みを行うという方法をとっています。

その結果、Siv3D Studio のエクスプローラに表示されているファイル、たとえば example フォルダを埋め込むことができないのです。

### main.wasm をリンクするときにファイルを埋め込むことの別のデメリット

main.wasm をリンクするときにファイルを埋め込むとなると、ビルドサーバに埋め込みを行いたいファイルを送信する必要があります。

これは、コンパイル時間の肥大とより激しい帯域の消費を伴う上、Siv3D Studio の外部にユーザのアセットファイルを漏らしてしまうことになりえます。

**Comment by Raclamusi** [comment]
詳しくありがとうございます。
Siv3D for Web と若干制約が異なることには気を付ける必要がありそうですね。
