### ISSUE TITLE
Favicon を変える

### ISSUE THREAD

**Issue by Reputeless** [nokotan/siv3d-studio#4]
- priority: medium

VSCode のロゴではなく Siv3D のロゴにする？
アイコンファイル、必要な形式を言ってくれれば用意します。

![image](https://user-images.githubusercontent.com/3108136/186840611-65a66633-9be6-46ec-8fdf-d7b0ea066047.png)

**Comment by nokotan** [comment]
起動設定には、カスタムアイコンの指定の項目がありません。

**Comment by nokotan** [comment]
サーバーのルートディレクトにあるのを見落としてました
