### ISSUE TITLE
ファイルがいくつか読み込まれない場合がある

### ISSUE THREAD

**Issue by Raclamusi** [nokotan/siv3d-studio#40]
### 問題

ワークスペースのファイルがいくつか読み込まれない場合があります（図1, 図2）。
キャッシュが残っている状態でよく発生します。

![image](https://user-images.githubusercontent.com/61970673/212529316-3b647cc8-7789-416b-ba74-fbcef36ddff0.png)
**図1　example/ 内の10ファイルが読み込まれていない。**

![image](https://user-images.githubusercontent.com/61970673/212531681-f10fbe41-1053-4397-aa9b-7b6967013351.png)
**図2　コンソールに出力されたエラー。ファイルの書き込みについてのエラーは1つしか出ていないが、これは `Promise.all` が最初のエラーで拒否される仕様であるためである。**

### 原因

いろいろ試して調べた結果、 `workspace.fs` のメソッドを並列に処理していることが原因のようです（ドキュメントとかは見つかってません）。
（直接的な原因は `workspace.fs.writeFile` ですが、 `workspace.fs.createDirectory` からもエラーが出ているので修正した方がよさそうです。）
キャッシュヒットすると各ファイルのフェッチが完了するタイミングが同じぐらいになり、 `writeFile` のタイミングが重なることでエラーが起きてそうな気がします。

フェッチだけ並列に処理して `writeFile` は最後に同期的に処理するようにしたり、 `writeFile` について排他制御するようにしたりするなどの対応が必要そうです。

**Comment by nokotan** [comment]
> いろいろ試して調べた結果、 workspace.fs のメソッドを並列に処理していることが原因のようです

ブラウザ上での JavaScript の並列処理は (明示的に WebWorker を使わない限り) マルチスレッドにならないので、原因としては考えづらいです。

> 直接的な原因は workspace.fs.writeFile ですが、 workspace.fs.createDirectory からもエラーが出ているので修正した方がよさそうです。

直接的な原因は workspace.fs.createDirectory です。エラー文の通り、すでに存在しているファイルやフォルダを作成しようとしているために、途中で初期ファイルのロード処理が中断されています。

初期ファイルのロード処理が条件によっては二重に行われてしまう場合があり、その時にこのようなエラーが発生することが判明しています。

**Comment by Raclamusi** [comment]
あれ、全然嘘ついてましたね。ごめんなさい。
Chrome のデバッガで `workspace.fs.writeFile` についての排他制御を追加した時に問題が一切発生しなくなったので、それが原因だと思い込んでました。

**Comment by nokotan** [comment]
再度この件に関して、vscode 本体のソースコードと照らし合わせながら調査してみました。

結論から述べると、存在しないディレクトリに複数のファイルを同時に `workspace.fs.writeFile` で書き込もうとする時に、それぞれの `workspace.fs.writeFile` の呼び出しでディレクトリを作ろうとしてしまうことが原因で、`workspace.fs.createDirectory` を await することで回避できるというのが正しそうです。

なので、

> フェッチだけ並列に処理して writeFile は最後に同期的に処理するようにしたり、 writeFile について排他制御するようにしたりするなどの対応が必要そうです。

は一つの正解になりうる解決策でした。

以下の私の発言には誤りがありました。申し訳ありませんが、ここて訂正させていただきます。

> ブラウザ上での JavaScript の並列処理は (明示的に WebWorker を使わない限り) マルチスレッドにならないので、原因としては考えづらいです。

`workspace.fs.writeFile` の呼び出し中に vscode Extension Host (WebWorker) -> メインスレッド -> vscode Extension Host (WebWorker) の順の RPC があるので、この処理はマルチスレッドの影響を受ける可能性がありました。

> 初期ファイルのロード処理が条件によっては二重に行われてしまう場合があり、その時にこのようなエラーが発生することが判明しています。

二重に行われた初期ファイルのロード処理でも EEXIST のエラーが出ていたので混同していました。この Issue の発生原因ではありません。
