### ISSUE TITLE
エディタのフォントサイズを簡単に変えられるようにする

### ISSUE THREAD

**Issue by Reputeless** [nokotan/siv3d-studio#41]
スクリーン共有時など、エディタのフォントを大きくしたいことがあります。
現在は「コマンドパレット」→「エディターのフォントを拡大」を使っていますが、より簡単な方法が実現できれば嬉しいです。

**Comment by nokotan** [comment]
Issue 報告ありがとうございます。

VSCode 側の機能として、[コマンドに任意のキーバインドを登録する機能](https://code.visualstudio.com/docs/getstarted/keybindings#_keyboard-shortcuts-editor)が用意されています。
そちらをお使いください。
