### ISSUE TITLE
Explorer から、余分な include フォルダを消す

### ISSUE THREAD

**Issue by Reputeless** [nokotan/siv3d-studio#5]
- priority: low

![image](https://user-images.githubusercontent.com/3108136/186841110-b8143996-6d68-441d-be91-46a64af3837d.png)

**Comment by nokotan** [comment]
すでに複数ファイル対応/ヘッダファイル対応が完了していますが、ヘッダファイルを使いたい時にこの場所に配置したらいいという動線を、ヘッダファイルを使わない人にとって、よくわからないフォルダがあることが望ましくないという配慮のために、削除するのは消極的です

**Comment by Reputeless** [comment]
そういうことなら残しておいて良さそう。
