### ISSUE TITLE
Gist のファイルを開くとき、ファイル名に % を含むファイルがあると読み込み処理がエラー終了する

### ISSUE THREAD

**Issue by Raclamusi** [nokotan/siv3d-studio#50]
Gist ID を指定して Gist を Siv3D Studio で開くとき、ファイル名に `%` を含むようなファイルがあると読み込みが中断され、それ以降の処理（ `Siv3D.data` や `.vscode/` の読み込みなど）が行われません。

`%` や `&` などの文字がファイル名に含まれている場合、そもそもビルドができません（ `emcc` から `Invalid filename` というエラーが出る）が、Gist からの読み込みでかつファイル名に `%` が含まれる場合は（開発者ツールを開かない限り）エラーすら表示されないため、`&` などの他の不正な文字が含まれている場合よりもエラーが起きていることが分かりにくい状況になります。

次のような Gist を Siv3D Studio で開くときに発生します。

https://gist.github.com/Raclamusi/c381e8e648a8d86bfc4808c9fb7284f2

**Comment by nokotan** [comment]
報告ありがとうございます。

`%` も `&` もファイル名にはほとんど使われることのない文字ゆえ、対応予定はありません。
