### ISSUE TITLE
Links?

### ISSUE THREAD

**Issue by martin12333** [nokotan/siv3d-studio#51]
https://marketplace.visualstudio.com/items?itemName=KamenokoSoft.wasm-playground ...
links here ... is it correct?

**Comment by nokotan** [comment]
Short answer: No, sadly.

This repository has the specifically customized version of <https://github.com/nokotan/wasm-playground> for <https://github.com/Siv3D/OpenSiv3D/>.

The link to the WebIDE is not public currently, respected to the decision of <https://github.com/Siv3D/OpenSiv3D/> owner.
