### ISSUE TITLE
左メニューから出す検索機能が正常に動作しない

### ISSUE THREAD

**Issue by Reputeless** [nokotan/siv3d-studio#8]
左メニューから出す検索機能が正常に動作しない

![image](https://user-images.githubusercontent.com/3108136/186907469-3d7a5171-35cc-44be-b11d-5a58b0374949.png)

![image](https://user-images.githubusercontent.com/3108136/186907483-fc37e37d-c587-473b-9239-13dfde137074.png)

**Comment by nokotan** [comment]
VSCode 試験的機能の型定義ファイルの更新が必要でした
更新して対応しています
