### ISSUE TITLE
左メニューの「ソース管理」「デバッグ(使わないなら)」タブを、非表示にできるならしたい

### ISSUE THREAD

**Issue by Reputeless** [nokotan/siv3d-studio#9]
左メニューで使える検索機能に不具合 (#8) があったり、そもそも Siv3D Studio では無意味な項目があるため

![image](https://user-images.githubusercontent.com/3108136/186907198-7331d520-ee2d-4578-9ae1-e2850b39a1be.png)

**Comment by nokotan** [comment]
個々のタブの表示/非表示は VSCode 自体の改変が必要になるので、対応に時間がかかります
アクティビティバー(これらのタブのコンテナ)自体を非表示にしてみます

**Comment by nokotan** [comment]
アクティビティバー自体を非表示にすると、エクスプローラが閉じられないために、モバイル環境でコード編集画面が狭くなりすぎます

**Comment by Raclamusi** [comment]
このように後から消すのはどうですか？（ #3 もついでに）

```javascript
// Node ごと消す
document.querySelector("div[aria-label='ソース管理 (Ctrl+Shift+G)']").parentNode.remove();
document.querySelector("div[aria-label='実行とデバッグ (Ctrl+Shift+D)']").parentNode.remove();
document.querySelector("div[aria-label='フィードバックをツイートする']").remove();
```

or

```javascript
// 表示を消す
document.querySelector("div[aria-label='ソース管理 (Ctrl+Shift+G)']").parentNode.style.display = "none";
document.querySelector("div[aria-label='実行とデバッグ (Ctrl+Shift+D)']").parentNode.style.display = "none";
document.querySelector("div[aria-label='フィードバックをツイートする']").style.display = "none";
```

**Comment by nokotan** [comment]
vscode 側がレイアウトに応じて、動的に DOM 要素を増やしたり減らしたりしています。
そのタイミングごとにその処理を走らせる必要があるので、その実装では応急処置程度になってしまいます。

**Comment by Raclamusi** [comment]
なるほど。
下のように CSS 規則を追加すればレイアウトを変更しても消えたままにはできますが、消した要素より下に配置されている「拡張機能」などの要素がレイアウト変更によって隠されるタイミングはそのままなので、違和感が残りますね。

```javascript
const siv3dStudioStyle = document.createElement("style");
document.head.appendChild(siv3dStudioStyle);
const { sheet } = siv3dStudioStyle;
sheet.insertRule('a[aria-label="ソース管理 (Ctrl+Shift+G)"] { display: none !important; }');
sheet.insertRule('a[aria-label="実行とデバッグ (Ctrl+Shift+D)"] { display: none !important; }');
sheet.insertRule('div[aria-label="フィードバックをツイートする"] { display: none !important; }');
```

（後で気づきましたが、これわざわざ JavaScript で CSS 規則を追加する必要なくて、 HTML ファイルに直書きするなり、スタイルシートを追加するなりでいいですね。）

**Comment by nokotan** [comment]
CSS 規則を追加するのは、動的に DOM 要素を追加されても要素を消したままにでいるので、ベターな解決策に感じます。
理想を言えば、日本語以外の他言語でも要素を消すことができればというところですが、当面は Siv3D Studio の方針としてその要件は求められないと考えたいです。

**Comment by Raclamusi** [comment]
CSS 規則で要素を消すと、すでに挙げたレイアウト変更によってアイコンが隠されるタイミングに違和感が残ること以外に、アクティビティバーやステータスバーを右クリックしたときに出てくるメニューと矛盾が発生して混乱のもとになるというデメリットがあります。

![image](https://user-images.githubusercontent.com/61970673/211139322-08100f13-66ac-40c8-bbf0-e0c2df0cfdf4.png)

対策としては、このメニューの項目についても CSS 規則を追加することで非表示にしてしまうことができます。

```css
li:has(span[aria-label="ソース管理"], span[aria-label="Source Control"]),
li:has(span[aria-label="実行とデバッグ"], span[aria-label="Run and Debug"]),
li:has(span[aria-label="フィードバック"], span[aria-label="Feedback"])
{
    display: none !important;
}
```

**Comment by Raclamusi** [comment]
別のアプローチとして、アクティビティバーやステータスバーを右クリックしたときに出てくるメニューを使って項目を非表示にするというものがあります。
このメニューではクリック（実際には mouseup ）した項目の表示/非表示を切り替えることができます。
これを自動化できれば使用しない項目を非表示にしておけます。

![image](https://user-images.githubusercontent.com/61970673/211140172-00dc3eb5-3df7-4cf4-a908-72f70a01466b.png)

無理やりマウスイベントを発火させて項目のチェックを外すコード例を以下に示します。

```javascript
{
    const uncheckItem = labels => {
        const item = document.querySelector(labels.map(label => `span[aria-label="${label}"]`).join()).parentElement;
        if (item.getAttribute("aria-checked") == "true") {
            item.dispatchEvent(new MouseEvent("mouseup", { bubbles: true, cancelable: true }));
        }
        // このままだとチェックがついてなかったときにメニューが表示されっぱなしになるので要改善
    };

    // アクティビティバーのメニュー表示
    document.querySelector("#workbench\\.parts\\.activitybar").firstElementChild.dispatchEvent(new MouseEvent("contextmenu"));
    // なぜか 100ms ぐらい待たないと mouseup イベントがすり抜ける（描画されてからでないとダメ？）
    setTimeout(() => {
        uncheckItem(["ソース管理", "Source Control"]);
        uncheckItem(["実行とデバッグ", "Run and Debug"]);

        // ステータスバーのメニュー表示
        document.querySelector("#workbench\\.parts\\.statusbar").dispatchEvent(new MouseEvent("contextmenu"));
        setTimeout(() => {
            uncheckItem(["フィードバック", "Feedback"]);
        }, 100);
    }, 100);
}
```

この方法では、 CSS 規則による方法のときのような問題が発生しないことに加えて、 `localStorage` などによって初回のみ実行するなどの処理をすることによってユーザが項目を表示させることもできるようになり、ユーザの自由度（？）が高くなります。

デメリットは、メニューが一瞬表示されることです（最悪）。
このデメリットを何とかできればかなりよい方法だと思います。
（というか、こんなメニューがあるなら設定ファイルでもいじれるようにしてくれればいいのに。）

**Comment by nokotan** [comment]
あまり良い解決方法では無いですが、無理やりユーザ設定を上書きすることで、アクティビティバーの表示などを任意の状態にできることがわかったので、一旦解決とします

https://github.com/nokotan/siv3d-studio/blob/main/index.html#L103
